version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=paracasa_db
      - MYSQL_USER=paracasa
      - MYSQL_PASSWORD=paracasa
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  paracasa:
    build: ./
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=paracasa
      - DATABASE_PASSWORD=paracasa
      - DATABASE_NAME=paracasa_db
      - DATABASE_PORT=3306

volumes:
  mysql_data:
  mysql_config:
